apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-bonus
  labels:
    app: argocd-app-bonus
spec:
  selector:
    matchLabels:
      app: argocd-app-bonus
  replicas: 1
  template:
    metadata:
      labels:
        app: argocd-app-bonus
    spec:
      containers:
      - name: wilsplayground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888