apiVersion: v1
kind: Service
metadata:
  name: argocd-app-service-bonus
  labels:
    app: argocd-app-bonus
spec:
  type: LoadBalancer
  ports:
    - port: 8889        
      targetPort: 8888
  selector:
    app: argocd-app-bonus