Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant"
  config.vm.define "ehasaluS" do |ehasaluS|
    ehasaluS.vm.box = "generic/centos9s"
    ehasaluS.vm.hostname = "ehasaluS"
    ehasaluS.vm.network "private_network", ip: "192.168.56.110"
    ehasaluS.vm.network "forwarded_port", guest: 6443, host: 6443
    ehasaluS.vm.network "forwarded_port", guest: 80, host: 80
    ehasaluS.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "ehasaluS"]
      vb.memory = "2048"   
      vb.cpus = 2          
    end

    ehasaluS.vm.provision "shell", privileged: true, inline: <<-SHELL
    curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode 644 --flannel-iface eth1
    chmod +x /vagrant/set_up_pods.sh
    /usr/bin/alias k=kubectl
    /usr/bin/sudo /usr/bin/systemctl stop firewalld
    /vagrant/set_up_pods.sh
      SHELL
  end
  
end
