# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "ehasaluS" do |ehasaluS|
    ehasaluS.vm.box = "generic/centos9s"
    ehasaluS.vm.hostname = "ehasaluS"
    ehasaluS.vm.network "private_network", ip: "192.168.56.110", nic_type: "virtio"
    
    ehasaluS.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "ehasaluS"]
      vb.memory = "1024"   
      vb.cpus = 1          
    end

    ehasaluS.vm.provision "shell", inline: <<-SHELL
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    curl -sfL https://get.k3s.io | sh -
    # add /usr/local/bin to secure path
    SHELL
  end

  config.vm.define "ehasaluSW" do |ehasaluSW|
    ehasaluSW.vm.box = "generic/centos9s"
    ehasaluSW.vm.hostname = "ehasaluSW"
    ehasaluSW.vm.network "private_network", ip: "192.168.56.111", nic_type: "virtio"

    ehasaluSW.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "ehasaluSW"]
      vb.memory = "1024"   
      vb.cpus = 1        
    end

    ehasaluSW.vm.provision "shell", inline: <<-SHELL
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    SHELL
  end

end
