# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant"
  config.vm.define "ehasaluS" do |ehasaluS|
    ehasaluS.vm.box = "generic/centos9s"
    ehasaluS.vm.hostname = "ehasaluS"
    ehasaluS.vm.network "private_network", ip: "192.168.56.110"
    
    ehasaluS.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "ehasaluS"]
      vb.memory = "2048"   
      vb.cpus = 2          
    end

    ehasaluS.vm.provision "shell", inline: <<-SHELL
    sudo firewall-cmd --permanent --add-port=6443/tcp
    sudo firewall-cmd --reload
    curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode 644
    SERVER_TOKEN=$(sudo cat /var/lib/rancher/k3s/server/node-token)
    echo ${SERVER_TOKEN} > /vagrant/server_token.txt
    echo alias k=kubectl >> /home/vagrant/.bashrc
    SHELL
  end

  config.vm.define "ehasaluSW" do |ehasaluSW|
    ehasaluSW.vm.box = "generic/centos9s"
    ehasaluSW.vm.hostname = "ehasaluSW"
    ehasaluSW.vm.network "private_network", ip: "192.168.56.111"

    ehasaluSW.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "ehasaluSW"]
      vb.memory = "2048"   
      vb.cpus = 2        
    end

    ehasaluSW.vm.provision "shell", inline: <<-SHELL
    SERVER_TOKEN=$(cat /vagrant/server_token.txt)

    # SERVER_TOKEN=$(ssh ehasaluS sudo cat /var/lib/rancher/k3s/server/node-token)
    curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${SERVER_TOKEN} sh -
    SHELL
  end

end
